FROM node:10.16.0

ENV APP_PORT 80
ENV MONGO_ENDPOINT="mongodb://tkg-mongo:27017/"
ENV MONGO_USER user
ENV MONGO_PASSWORD pass

VOLUME ["/tracking-log-graph"]
WORKDIR /tracking-log-graph
RUN npm install

EXPOSE 80

CMD ["npm", "start"]
