version: '3.7'

services:
  tkg-app:
    build:
      context: .
      dockerfile: Dockerfile-app
    ports:
      - 80:80
    init: true
    tty: true

  tkg-mongo:
    build:
      context: .
      dockerfile: Dockerfile-mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ../strage/db:/data/db
      - ../strage/configdb:/data/configdb
