export default {
  ON_DROP: 'ON_DROP',
  ON_SELECT_CUSTOMER: 'ON_SELECT_CUSTOMER',
  ON_CHANGE_FORM: 'ON_CHANGE_FORM',
  ON_TURNON_RADIO: 'ON_TURNON_RADIO',
  RECEIVE_TEMPLATE: 'RECEIVE_TEMPLATE',
  RECEIVE_ERROR: 'RECEIVE_ERROR',
}
